name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below.

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which part of the app is affected?
      options:
        - Auth
        - Dashboard
        - Invoices
        - Expenses
        - Clients
        - Reports
        - Settings
        - Onboarding
        - Navigation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What went wrong?
      placeholder: Clear description of the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: The app should...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: Instead, the app...
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - iOS
        - Android
        - Web
        - All platforms
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Device, OS version, app version
      placeholder: |
        - Device: iPhone 15 Pro
        - OS: iOS 17.2
        - App version: 1.0.0

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any relevant error messages or stack traces
      render: shell
