// This is a stub file for CI builds.
// The real firebase_options.dart is generated by FlutterFire CLI
// and contains sensitive project configuration.
//
// To generate the real file, run:
//   flutterfire configure
//
// This stub allows flutter analyze to pass in CI without real credentials.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // This stub returns iOS options by default for CI
    return ios;
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'stub-api-key',
    appId: 'stub-app-id',
    messagingSenderId: 'stub-sender-id',
    projectId: 'stub-project-id',
    storageBucket: 'stub-bucket',
    iosBundleId: 'com.example.gigledger',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'stub-api-key',
    appId: 'stub-app-id',
    messagingSenderId: 'stub-sender-id',
    projectId: 'stub-project-id',
    storageBucket: 'stub-bucket',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'stub-api-key',
    appId: 'stub-app-id',
    messagingSenderId: 'stub-sender-id',
    projectId: 'stub-project-id',
    storageBucket: 'stub-bucket',
    authDomain: 'stub-project.firebaseapp.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'stub-api-key',
    appId: 'stub-app-id',
    messagingSenderId: 'stub-sender-id',
    projectId: 'stub-project-id',
    storageBucket: 'stub-bucket',
    iosBundleId: 'com.example.gigledger',
  );
}
